"""empty message

Revision ID: 687747cff158
Revises: 0c8f178e6ff7
Create Date: 2020-05-12 11:40:47.058280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687747cff158'
down_revision = '0c8f178e6ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
